# Generated by Django 5.2.5 on 2025-08-13 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(help_text='Title of the movie', max_length=255)),
                ('director', models.CharField(help_text='Director name', max_length=255)),
                ('release_year', models.IntegerField(help_text='Year of release', validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2030)])),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='TMDb/OMDb metadata (poster URL, ratings, synopsis, cast, genre, etc.)')),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Watching'), ('watched', 'Watched'), ('abandoned', 'Abandoned')], default='want_to_watch', help_text='Watch status', max_length=20)),
                ('mood_tags', models.JSONField(blank=True, default=list, help_text='Mood tags (manual or AI-generated)')),
                ('user_rating', models.IntegerField(blank=True, help_text='User-assigned rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user_notes', models.TextField(blank=True, help_text='User notes')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last metadata refresh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movie_name'], name='movies_movi_movie_n_2a050f_idx'), models.Index(fields=['director'], name='movies_movi_directo_fcc683_idx'), models.Index(fields=['release_year'], name='movies_movi_release_81d5c9_idx'), models.Index(fields=['status'], name='movies_movi_status_ba6bc6_idx'), models.Index(fields=['last_updated'], name='movies_movi_last_up_09727f_idx')],
            },
        ),
    ]
