# Generated by Django 5.2.5 on 2025-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list, help_text='Mood tags (manual or AI-generated)', null=True),
        ),
    ]
